name: Quester
version: ${yml.version}
description: Quester provides ability to create highly customizable quests directly in game.
author: raGan
website: http://dev.bukkit.org/server-mods/quester/
main: com.gmail.molnardad.quester.Quester
softdepend: [Vault, Citizens, EpicBossReloaded, Denizen]
commands:
    q:
        description: Main (and only) quester command.
        aliases: [quest, quester]
