general:
  verbose-logging: true
  save-interval: 15
  debug-info: false
  disable-usecmds: false
objectives:
  show-only-current: true
  break:
    no-drops: false
    subtract-on-place: true
  collect:
    remove-on-pickup: true
    subtract-on-drop: false
quests:
  only-first: true
  show-objectives: true
