general:
  verbose-logging: true
  save-interval: 15
  debug-info: false
  disable-usecmds: false
objectives:
  show-only-current: true
  break:
    no-drops: false
    subtract-on-place: true
  collect:
    remove-on-pickup: true
    subtract-on-drop: false
quests:
  show-objectives: true
  messages:
    start-show: true
    cancel-show: true
    done-show: true
    objective-show: true
ranks:
  Quester: 0
  Apprentice-Quester: 25
  Master-Quester: 50
