name: Quester
version: 0.5.3d1
description: Quester provides ability to create highly customizable quests directly in game.
author: raGan
website: http://www.pc-isle.com
main: com.gmail.molnardad.quester.Quester
commands:
    q:
        description: Main (and only) quester command.
        aliases: [quest, quester]
