name: Quester
version: 0.3.2
description: Quester provides ability to create custom quests, consisting of ever increasing number of objective and reward types.
author: raGan
website: http://www.pc-isle.com
main: com.gmail.molnardad.quester.Quester
commands:
    quest:
        description: Main (and only) quester command.
        aliases: [q, quester]
